name: Update repo.json on Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (e.g., 1.0.0, not with v)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  update-repo-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set release tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Run blender-repo-json-action
        uses: ShinoMythmaker/blender-repo-json-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          RELEASE_TAG: ${{ steps.tag.outputs.tag_name }}

      - name: Commit and push repo.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add repo.json
          git commit -m "Update repo.json for release ${{ steps.tag.outputs.tag_name }}"
          git push origin HEAD:${{ github.event.repository.default_branch }}